### ISSUE TITLE
Copied Formspree link

### ISSUE THREAD

**Issue by njkaiser** [RAHUL-B-PILLAI/portfoli#1]
Hey Rahul,

FYI, it looks like when you cloned my portfolio page, you never changed the Formspree link for the form at the bottom. That Formspree link basically sends an email to my personal address through my Formspree account, thus I got your test message recently :)

When you get the chance, could you please swap out that Formspree link with one of your own? Thanks in advance!

**Comment by RAHUL-B-PILLAI** [comment]
hey Njkaiser,
Firstly of I would like to thank you for bringing the thing to my attention. I really like portfolio hence motivated me to build something similar. I will rectify the mistake and I am sorry for any inconvenience caused due to this. Thank you for understanding. Keep doing your good work so that it become a source of motivation for people like me :).
